### ISSUE TITLE
Cannot add ED25519 Key

### ISSUE THREAD

**Issue by ALuongIBM** [ibm-cloud-docs/vpc-on-classic-vsi#3]
Hi there, I'm trying to paste my public key into the SSH Keys, however I keep getting the error `The public key can not be parsed and is invalid.`This doesn't happen with an RSA 4096 key but happens with an ED25519 key.  Is there no support for `ssh-ed25519` keys?

**Comment by gudrun-wolfgram** [comment]
@ALuongIBM Did you get this item figured out?

**Comment by gudrun-wolfgram** [comment]
@ALuongIBM I've updated this topic to include the RSA key size requirement. 

SSH Keys
https://cloud.ibm.com/docs/vpc-on-classic-vsi?topic=vpc-on-classic-vsi-ssh-keys

_Your SSH key must be an RSA key with a key size of either 2048 bits or 4096 bits._
