### ISSUE TITLE
Adding a SSK key of (1024) bits fails 

### ISSUE THREAD

**Issue by hkantare** [ibm-cloud-docs/vpc-on-classic-vsi#4]
I tried generating an ssh key of 1024 bit sssh-keygen -t rsa -b 1024.

When I try adding that SSHKEY in VPC it fails with
"The information given was invalid, malformed, or missing a required field."

**Comment by gudrun-wolfgram** [comment]
@hkantare Did you get this item figured out?

**Comment by gudrun-wolfgram** [comment]
@hkantare I've updated this topic to include the RSA key size requirement. 

SSH Keys
https://cloud.ibm.com/docs/vpc-on-classic-vsi?topic=vpc-on-classic-vsi-ssh-keys

_Your SSH key must be an RSA key with a key size of either 2048 bits or 4096 bits._
