### ISSUE TITLE
Configuring virtual server settings for improved network performance - should be on Gen2 in addition to Gen1

### ISSUE THREAD

**Issue by AliseATX** [ibm-cloud-docs/vpc-on-classic-vsi#9]
Hi there, 

MTU customization is supported on Gen2 VCP so those documents should be updated to reflect this . 

https://cloud.ibm.com/docs/vpc-on-classic-vsi?topic=vpc-on-classic-vsi-configuring-network-performance

Thanks,
Alise

**Comment by sheltons** [comment]
Started a draft in the staging repo to move this over to Gen 2. 

This issue can be closed, because it cannot be worked on from the production repository at all. Thanks for bringing it to our attention!
